# : Manager [[[

[manager]
cwd = { fg = "#dee3e5" }

# Tab
tab_active = { fg = "#00363e", bg = "#82d3e2", bold = true }
tab_inactive = { fg = "#9eefff", bg = "#001f24" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#758cff", bg = "#758cff" }
marker_cut = { fg = "#dbe1ff", bg = "#dbe1ff" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#bbc5eb", bg = "#bbc5eb" }

# Count
count_copied = { fg = "#0f1a37", bg = "#dbe1ff" }
count_cut = { fg = "#0f1a37", bg = "#dbe1ff" }
count_selected = { fg = "#00363e", bg = "#bbc5eb" }

# Border
border_symbol = "│"
border_style  = { fg = "#82d3e2" }

# : ]]]


# : Status [[[

[status]
separator_open = "🭁"
separator_close = "🭠"
separator_style = { bg = "#00363e", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#82d3e2", fg = "#00363e", bold = true }
normal_alt  = { bg = "#3f484a", fg = "#bfc8ca" }

# Select mode
select_main = { bg = "#b1cbd1", fg = "#1c3438", bold = true }
select_alt  = { bg = "#3f484a", fg = "#bfc8ca" }

# Unset mode
unset_main = { bg = "#bbc5eb", fg = "#252f4d", bold = true }
unset_alt  = { bg = "#3f484a", fg = "#bfc8ca" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#82d3e2", bg = "#343a3c" }
progress_error = { fg = "#ffb4ab", bg = "#343a3c" }

# Permissions
permissions_t = { fg = "#568793" }
permissions_w = { fg = "#4560c8" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#4261ff" }
permissions_s = { fg = "#05d6ff" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#82d3e2" }
active = { fg = "#bbc5eb", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#82d3e2" }
value = { fg = "#dee3e5" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#82d3e2", bg = "#00363e" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#82d3e2" }
title = {}
hovered = { fg = "#dbe1ff", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#343a3c" }
cand = { fg = "#82d3e2" }
rest = { fg = "#00363e" }
desc = { fg = "#dee3e5" }
separator = " ▶ "
separator_style = { fg = "#dee3e5" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#dee3e5" }
run = { fg = "#dee3e5" }
footer = { fg = "#1c3438", bg = "#b1cbd1" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#bbc5eb" }
title_warn = { fg = "#82d3e2" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#dee3e5" },
    { name = "*/", fg = "#82d3e2" },
]

# : ]]]
