# : Manager [[[

[manager]
cwd = { fg = "#e1e2e9" }

# Tab
tab_active = { fg = "#05305f", bg = "#a8c8ff", bold = true }
tab_inactive = { fg = "#d5e3ff", bg = "#001b3c" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#e675fb", bg = "#e675fb" }
marker_cut = { fg = "#f8d8fe", bg = "#f8d8fe" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#dbbce1", bg = "#dbbce1" }

# Count
count_copied = { fg = "#28132f", bg = "#f8d8fe" }
count_cut = { fg = "#28132f", bg = "#f8d8fe" }
count_selected = { fg = "#05305f", bg = "#dbbce1" }

# Border
border_symbol = "│"
border_style  = { fg = "#a8c8ff" }

# : ]]]


# : Status [[[

[status]
separator_open = "🭁"
separator_close = "🭠"
separator_style = { bg = "#05305f", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#a8c8ff", fg = "#05305f", bold = true }
normal_alt  = { bg = "#43474e", fg = "#c4c6cf" }

# Select mode
select_main = { bg = "#bdc7dc", fg = "#273141", bold = true }
select_alt  = { bg = "#43474e", fg = "#c4c6cf" }

# Unset mode
unset_main = { bg = "#dbbce1", fg = "#3e2845", bold = true }
unset_alt  = { bg = "#43474e", fg = "#c4c6cf" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#a8c8ff", bg = "#37393e" }
progress_error = { fg = "#ffb4ab", bg = "#37393e" }

# Permissions
permissions_t = { fg = "#5972a7" }
permissions_w = { fg = "#a252b2" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#dd43fa" }
permissions_s = { fg = "#3c7dff" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#a8c8ff" }
active = { fg = "#dbbce1", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#a8c8ff" }
value = { fg = "#e1e2e9" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#a8c8ff", bg = "#05305f" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#a8c8ff" }
title = {}
hovered = { fg = "#f8d8fe", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#37393e" }
cand = { fg = "#a8c8ff" }
rest = { fg = "#05305f" }
desc = { fg = "#e1e2e9" }
separator = " ▶ "
separator_style = { fg = "#e1e2e9" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#e1e2e9" }
run = { fg = "#e1e2e9" }
footer = { fg = "#273141", bg = "#bdc7dc" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#dbbce1" }
title_warn = { fg = "#a8c8ff" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#e1e2e9" },
    { name = "*/", fg = "#a8c8ff" },
]

# : ]]]
