format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character"""

palette = 'colors'

[palettes.colors]
mustard = '#af8700' # example
color1 = '{{colors.primary_fixed_dim.default.hex}}'
color2 = '{{colors.on_primary.default.hex}}'
color3 = '{{colors.on_surface_variant.default.hex}}'
color4 = '{{colors.surface_container.default.hex}}'
color5 = '{{colors.on_primary.default.hex}}'
color6 = '{{colors.surface_dim.default.hex}}'
color7 = '{{colors.surface.default.hex}}'
color8 = '{{colors.primary.default.hex}}'
color9 = '{{colors.tertiary.default.hex}}'

[character]
success_symbol = "[❯❯](color9 bold)"
error_symbol = "[❯❯](@{error})"
vimcmd_symbol = "[❮❮](#f9e2af)"

[directory]
style = "blue"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = 'bold'
untracked = '?'
staged = '[++\($count\)](green)'
modified = '!'
deleted = '✘'
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
conflicted = ''

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[$symbol($version)]($style)"
style = "yellow bold"
symbol = ''
version_format = 'v${raw}'
detect_extensions = ['py', 'ipynb']
detect_files = ['.python-version', 'Pipfile', '__init__.py', 'pyproject.toml', 'requirements.txt', 'setup.py', 'tox.ini']
python_binary = ['python', 'python3', 'python2']

[rust]
format = "[$symbol($version)]($style) "
style = "bold red"
symbol = ''
version_format = 'v${raw}'
detect_extensions = ['rs']
detect_files = ['Cargo.toml']

[C]
format = "[$symbol($version(-$name) )]($style) "
style = "bold 149"
symbol = ''
detect_extensions = ['c', 'h']
commands = [ [ 'cc', '--version' ], [ 'gcc', '--version' ], [ 'clang', '--version' ] ]
version_format = 'v${raw}'
