[pyprland]
plugins = [
  "scratchpads",
]

[scratchpads.btop]
animation = "fromLeft"
command = "kitty --class kitty-dropterm -T btop -e btop"
class = "kitty-dropterm"
size = "50% 75%"
unfocus = "hide"
max_size = "1920px 100%"
margin = 40
lazy = true

[scratchpads.excalidraw]
animation = "fromRight"
command = "/usr/bin/chromium --profile-directory=Default --app-id=dnfpoenibinnbbckgbhendmlljoobcfg"
class = "chrome-dnfpoenibinnbbckgbhendmlljoobcfg-Default"
size = "50% 75%"
unfocus = "hide"
max_size = "1920px 100%"
margin = 40
lazy = true

[scratchpads.signal]
animation = "fromBottom"
command = "signal-desktop"
class = "signal"
size = "50% 70%"
unfocus = "hide"
max_size = "1920px 100%"
margin = 40
lazy = true

